(function(c){function d(){}function o(a){B=[a]}function q(a,b,g,f){try{f=a&&a.apply(b.context||b,g)}catch(h){f=false}return f}function C(a){return/\?/.test(a)?"&":"?"}function J(a){function b(k){K++||(L(),t&&(x[i]={s:[k]}),h&&(k=h.apply(a,[k])),q(a.success,a,[k,r]),q(f,a,[a,r]))}function g(k){K++||(L(),t&&k!=y&&(x[i]=k),q(a.error,a,[a,k]),q(f,a,[a,k]))}a=c.extend({},M,a);var f=a.complete,h=a.dataFilter,z=a.callbackParameter,N=a.callback,n=a.cache,t=a.pageCache,l=a.charset,i=a.url,u=a.data,W=a.timeout,
O,K=0,L=d,e,D,U;return a.abort=function(){!K++&&L()},q(a.beforeSend,a,[a])===false||K?a:(i=i||v,u=u?typeof u=="string"?u:c.param(u,a.traditional):v,i+=u?C(i)+u:v,z&&(i+=C(i)+encodeURIComponent(z)+"=?"),!n&&!t&&(i+=C(i)+"_"+(new Date).getTime()+"="),i=i.replace(/=\?(&|$)/,"="+N+"$1"),t&&(O=x[i])?O.s?b(O.s[0]):g(O):(E[N]=o,e=c(j)[0],e.id=P+V++,l&&(e[F]=l),Q&&Q.version()<11.6?((D=c(j)[0]).text="document.getElementById('"+e.id+"')."+w+"()"):(e[R]=R),!(A in e)&&G in e&&(e.htmlFor=e.id,e.event=s),e[A]=
e[w]=e[G]=function(k){if(!e[S]||/loaded|complete/.test(e[S])){try{e[s]&&e[s]()}catch(X){}k=B;B=0;k?b(k[0]):g(T)}},e.src=i,L=function(){U&&clearTimeout(U);e[G]=e[A]=e[w]=null;p[m](e);D&&p[m](D)},p[H](e,I),D&&p[H](D,I),U=W>0&&setTimeout(function(){g(y)},W)),a)}var R="async",F="charset",v="",T="error",H="insertBefore",P="_jqjsp",s="onclick",w="on"+T,A="onload",G="onreadystatechange",S="readyState",m="removeChild",j="<script>",r="success",y="timeout",E=window,p=c("head")[0]||document.documentElement,
I=p.firstChild,x={},V=0,B,M={callback:P,url:location.href},Q=E.opera;J.setup=function(a){c.extend(M,a)};c.jsonp=J})(jQuery);var suggestionsearch_enable=function(){jQuery("#navbar-query").searchAutocomplete({maxResults:6,alwaysScrollIntoView:false,resultsDiv:jQuery("#navbar-suggestionsearch"),keyboardControl:true});jQuery("#navbar-query").attr("autocomplete","off");repositionSuggestionSearch()},repositionSuggestionSearch=function(){var c=jQuery("#navbar-query"),d=c.position(),o=c.width();c=c.height();jQuery("#navbar-suggestionsearch").css({left:d.left+0+"px",top:d.top+c+11+"px",width:o+115+"px"})},suggestionsearch_disable=
function(){jQuery("#navbar-query").stopSearchAutocomplete({resultsDiv:jQuery("#navbar-suggestionsearch")});jQuery("#navbar-query").attr("autocomplete","on")},suggestionsearch_dropdown_choice=function(c){"all"==c.value?suggestionsearch_enable():suggestionsearch_disable()};function trackAndClick(c,d,o){(new Image).src="/rg/"+c+"/"+d+"/images/b.gif";setTimeout(function(){document.location=o.href},0);return false}
jQuery(document).ready(function(){var c=jQuery('#nb_search select[name="s"]');if(c.length>0){c=c[0];suggestionsearch_dropdown_choice(c)}});
(function(c){c.fn.searchAutocomplete=function(d){function o(a){q();jQuery(a).addClass("highlighted")}function q(){j.find("a.highlighted").removeClass("highlighted")}function C(){var a=j.find("a.highlighted");a.length>0?a.first().get(0).click():jQuery("#navbar-form").submit()}function J(){if(j.find("a").length>0){var a=j.find("a.highlighted");if(a.length>0){a=a.first();var b=a.prev("a");b.length>0&&b.first().addClass("highlighted");a.removeClass("highlighted")}}}function R(){var a=j.find("a");if(a.length>
0){var b=j.find("a.highlighted");if(b.length>0){a=b.first();b=a.next("a");if(b.length>0){b.first().addClass("highlighted");a.removeClass("highlighted")}}else a.first().addClass("highlighted")}}function F(){repositionSuggestionSearch();j.css("display","block")}function v(){j.css("display","none")}function T(){j.css({opacity:0,filter:"alpha(opacity=0)"})}function H(a){if(a){a=a.toLowerCase();if(a.length>20)a=a.substr(0,20);a=a.replace(/^\s*/,"").replace(/[ ]+/g,"_");if(M.test(a))a=a.replace(/[\u00e0\u00c0\u00e1\u00c1\u00e2\u00c2\u00e3\u00c3\u00e4\u00c4\u00e5\u00c5\u00e6\u00c6]/g,
"a").replace(/[\u00e7\u00c7]/g,"c").replace(/[\u00e8\u00c8\u00e9\u00c9\u00ea\u00ca\u00eb\u00cb]/g,"e").replace(/[\u00ec\u00cd\u00ed\u00cd\u00ee\u00ce\u00ef\u00cf]/g,"i").replace(/[\u00f0\u00d0]/g,"d").replace(/[\u00f1\u00d1]/g,"n").replace(/[\u00f2\u00d2\u00f3\u00d3\u00f4\u00d4\u00f5\u00d5\u00f6\u00d6\u00f8\u00d8]/g,"o").replace(/[\u00f9\u00d9\u00fa\u00da\u00fb\u00db\u00fc\u00dc]/g,"u").replace(/[\u00fd\u00dd\u00ff]/g,"y").replace(/[\u00fe\u00de]/g,"t").replace(/[\u00df]/g,"ss");return a=a.replace(/[\W]/g,
"")}return""}function P(){w(m.val())}function s(a,b){if(a&&b&&b.length<=a.length&&a.substr(0,b.length)===b)return true;return false}function w(a){var b=H(a);if(b.length==0){v();E=y=r=""}else if(b!==r){F();c.jsonp({charset:"UTF-8",dataType:"jsonp",callback:"imdb$"+b,url:"//sg.media-imdb.com/suggests/"+b.substr(0,1)+"/"+b+".json",error:function(g,f){if(f==="error"&&b.length>1){E=b;s(r,y)?G(b):w(b.substr(0,b.length-1))}},success:function(g){A(g,b);y=b;p=g},pageCache:pageCacheSetting});r=b}}function A(a,
b){if(r===b){var g=b="";if(typeof c("#nb_search").attr("data-hostname")!="undefined")g="http://"+c("#nb_search").attr("data-hostname");for(var f=0;f<a.d.length&&f<V;f+=1){var h=a.d[f],z="";if(c("#megaMenu").length)z="nv_";var N=z+"sr_"+(f+1),n=h.id,t="film-40x54.png",l;if(s(n,"nm")){l=g+"/name/"+n+"/";t="people-40x54.png"}else if(s(n,"tt"))l=g+"/title/"+n+"/";else if(s(n,"http://"))l=n;if(l){n={url:l,title:h.l,detail:h.s,placeholder:t};if(h.i)n.img={url:h.i[0].replace("._V1_.jpg","._V1._SX40_CR0,0,40,54_.jpg"),
width:40,height:54};if(h.y)n.extra="("+h.y+")";b+=S(n,N)}}if(b.length>0){F();l=m.val();a=l.replace(B," ");l=jQuery("<div/>").text(l).html();b+='<a class="moreResults" href="';b+=g+"/find?s=all&q="+a+"&ref_="+z+'sr_sm">';b+='<span class="message">See all results for "<span class="query">'+l+'</span>"</span>&nbsp;<span class="raquo">&raquo;</span>';b+="</a>";j.html(b);j.find("a").hover(function(){o(this)},function(){})}}}function G(a){for(var b=[],g=[],f=0;f<p.d.length;f+=1){var h=p.d[f];H(h.l).match(a)?
b.push(h):g.push(h)}A({d:b.concat(g)},a)}function S(a,b){b='<a href="'+a.url+"?ref_="+b+'" class="poster"';b+=">";if(a.img){b+='<img src="'+a.img.url+'"';b+=" style=\"background:url('http://i.media-imdb.com/images/mobile/"+a.placeholder+"')\"";if(a.img.width&&a.img.height)b+=' width="'+a.img.width+'" height="'+a.img.height+'"';b+=">"}else if(a.placeholder)b+='<img src="http://i.media-imdb.com/images/mobile/'+a.placeholder+'">';b+='<div class="suggestionlabel">';b+='<span class="title">'+a.title+"</span>";
if(a.extra)b+=' <span class="extra">'+a.extra+"</span>";if(a.detail)b+='<div class="detail">'+a.detail+"</div>";b+="</div></a>";return b}if(typeof d=="undefined")d={};var m=jQuery(this),j="resultsDiv"in d?d.resultsDiv:jQuery("#autocomplete"),r="",y="",E="",p="",I,x,V="maxResults"in d?d.maxResults:3,B=/[^\w\u00e0\u00c0\u00e1\u00c1\u00e2\u00c2\u00e3\u00c3\u00e4\u00c4\u00e5\u00c5\u00e6\u00c6\u00e7\u00c7\u00e8\u00c8\u00e9\u00c9\u00ea\u00ca\u00eb\u00cb\u00ec\u00cd\u00ed\u00cd\u00ee\u00ce\u00ef\u00cf\u00f0\u00d0\u00f1\u00d1\u00f2\u00d2\u00f3\u00d3\u00f4\u00d4\u00f5\u00d5\u00f6\u00d6\u00f8\u00d8\u00f9\u00d9\u00fa\u00da\u00fb\u00db\u00fc\u00dc\u00fd\u00dd\u00ff\u00fe\u00de\u00df]/g,
M=/[\u00e0\u00c0\u00e1\u00c1\u00e2\u00c2\u00e3\u00c3\u00e4\u00c4\u00e5\u00c5\u00e6\u00c6\u00e7\u00c7\u00e8\u00c8\u00e9\u00c9\u00ea\u00ca\u00eb\u00cb\u00ec\u00cd\u00ed\u00cd\u00ee\u00ce\u00ef\u00cf\u00f0\u00d0\u00f1\u00d1\u00f2\u00d2\u00f3\u00d3\u00f4\u00d4\u00f5\u00d5\u00f6\u00d6\u00f8\u00d8\u00f9\u00d9\u00fa\u00da\u00fb\u00db\u00fc\u00dc\u00fd\u00dd\u00ff\u00fe\u00de\u00df]/,Q="keyboardControl"in d?d.keyboardControl:false;alwaysScrollIntoView="alwaysScrollIntoView"in d?d.alwaysScrollIntoView:true;
pageCacheSetting=c.browser.msie==true?false:true;c(document).mousedown(function(a){x=c(a.target)});m.focus(function(){alwaysScrollIntoView&&this.scrollIntoView();if(m.val().length>0){w(m.val());F()}});m.blur(function(){I=x.parents("#navbar-suggestionsearch").length?setTimeout(T,300):setTimeout(v,300)});m.keydown(function(a){if(Q)if(a.keyCode==38){m.focus();J();return false}else if(a.keyCode==40){m.focus();R();return false}else if(a.keyCode==13){C();return false}else if(a.keyCode==27){q();v();return false}m.focus();
I=setTimeout(P,0)})};c.fn.stopSearchAutocomplete=function(d){if(typeof d=="undefined")d={};var o=jQuery(this);d="resultsDiv"in d?d.resultsDiv:jQuery("#autocomplete");o.unbind("focus");o.unbind("blur");o.unbind("keydown");d.css("display","none")}})(jQuery);
