if(!Array.prototype.map)Array.prototype.map=function(f,h){var d,a;if(this==null)throw new TypeError(" this is null or not defined");var b=Object(this),e=b.length>>>0;if({}.toString.call(f)!="[object Function]")throw new TypeError(f+" is not a function");if(h)d=h;h=new Array(e);for(a=0;a<e;){var g;if(a in b){g=b[a];g=f.call(d,g,a,b);h[a]=g}a++}return h};
(function(f,h){function d(g,c){var j,l=g;if(typeof c==="function")c=c(g);if(typeof c==="string"||typeof c==="number"){b&&consoleLog("create text node : "+c,"jsonml");g.append(c)}else if(f.isPlainObject(c)){b&&consoleLog("attach attributes","jsonml");f.each(c,function(k,i){try{g.attr(k,i)}catch(m){e&&consoleLog(g[0].nodeName+" rejected assignment of attribute : "+k+"="+i,"jsonml")}})}else if(c instanceof Array){f.each(c,function(k,i){if(typeof i==="function")i=i(g);if(k===0&&typeof i==="string"){b&&
consoleLog("create new element : "+i,"jsonml");l=j=f(h.createElement(i))}else d(l,i)});j&&g.append(j)}else if(c)b&&consoleLog("unknown data type","jsonml");else b&&consoleLog("noop","jsonml")}function a(g){var c=[],j,l,k,i,m={};if(g.length===1){j=g[0].nodeType;l=g[0].nodeName;k=g[0].nodeValue;i=g[0].attributes;if(j==1){b&&consoleLog("encode element : "+l,"jsonml");c.push(l);if(i.length>0){f.each(i,function(n,o){m[o.name]=o.value});c.push(m)}c.push(a(g.contents()))}else if(j==3){b&&consoleLog("encode text : "+
k,"jsonml");c=k}else if(j==8)b&&consoleLog("ignoring comment : "+k,"jsonml");else b&&consoleLog("unsupported node type","jsonml")}else g.each(function(){var n=a(f(this));typeof n==="string"&&c.length===0&&c.push(undefined);c.push(n)});return c}var b=h.location.hash.search("jsonml_debug=1")>=0,e=1;f.fn.jsonml=function(g){var c=f(this);if(g){d(c,g);c.trigger("jsonml_ready");return c}else return a(c.contents())};f.jsonml={toDom:function(g){var c=f("<div>");c.jsonml(g);return c.contents()},fromDom:a}})(jQuery,
document);
(function(f){var h={tmpl_base:function(d){d=f.extend({text:null,href:null,classes:[],attrs:{},type:null,size:null,glyph:null},d);d.classes.push("btn2");d.size&&d.classes.push(d.size);d.type&&d.classes.push(d.type);d.glyph&&d.classes.push("btn2_glyph_on");d.text&&d.classes.push("btn2_text_on");return["a",{"class":d.classes.join(" "),onclick:""},d.attrs,d.href&&{href:d.href},this.tmpl_glyph(d),this.tmpl_text(d)]},tmpl_glyph:function(d){return["span",{"class":"btn2_glyph"},d.glyph]},tmpl_text:function(d){return["span",{"class":"btn2_text"},
d.text]},tmpl_spin:function(){return["div",{"class":"btn2_spin"}]},tmpl_check:function(){return["div",{"class":"btn2_check"},"&#x2714;"]},tmpl_plus:function(){return["div",{"class":"btn2_plus"},"+"]},tmpl_error:function(){return["div",{"class":"btn2_error"},"!"]}};window.imdb_btn2={templates:h};f.widget("ui.imdb_btn2",{options:{templates:h,model:null},_create:function(){var d=this.element,a=this.options,b=d.attr("data-size"),e=d.attr("data-type"),g=(d.attr("data-classes")||"").split(" ");this.templates=
a.templates;if(this.model=a.model){this.model.size=this.model.size||b;this.model.type=this.model.type||e;this.model.classes=this.model.classes||g;d.children().remove();d.jsonml(this.templates.tmpl_base(this.model))}d.addClass("btn2_wrapper btn2_active")},modifyGlyph:function(d){var a=this.element,b=f(".btn2",a);this.model.glyph=d;d!=null?b.addClass("btn2_glyph_on"):b.removeClass("btn2_glyph_on");f(".btn2_glyph",a).replaceWith(f.jsonml.toDom(this.templates.tmpl_glyph(this.model)))},modifyText:function(d){var a=
this.element,b=f(".btn2",a);this.model.text=d;d!=null?b.addClass("btn2_text_on"):b.removeClass("btn2_text_on");f(".btn2_text",a).replaceWith(f.jsonml.toDom(this.templates.tmpl_text(this.model)))}})})(jQuery);(function(f){function h(){var a=document.cookie.split(/\;\s*/),b;for(b in a)if(a.hasOwnProperty(b))if(a[b].search(/^id=/)>=0)return true;return false}var d={glyph:{loading:imdb_btn2.templates.tmpl_spin(),"in":imdb_btn2.templates.tmpl_check(),out:null,pending:imdb_btn2.templates.tmpl_spin(),error:imdb_btn2.templates.tmpl_error()},text:{loading:"Loading","in":"Watchlist",out:"Add to Watchlist",pending:"Watchlist",error:"Unavailable"},title:{loading:"Loading watchlist data","in":"Click to remove from watchlist",
out:"Click to add to watchlist",pending:"Updating watchlist data",error:"Watchlist currently unavailable"}};f.widget("ui.wlb_lite_base",f.ui.imdb_btn2,{options:{model:{assets:d,glyph:d.glyph.loading,text:d.text.loading,tconst:null,state:"loading"}},_create:function(){var a=this,b=a.element,e=a.options.model;if(!e.tconst)e.tconst=b.attr("data-tconst");if(!e.caller_name)e.caller_name=b.attr("data-caller-name")||b.closest("[data-caller-name]").attr("data-caller-name");f.ui.imdb_btn2.prototype._create.apply(this,
arguments);b.addClass("wlb_lite");if(e.tconst){h()||a._set_state("out");f("a.btn2",b).bind("click.wlb_lite",function(){a._request_toggle()});a.global_handlers={wlb_async_init:function(g,c){a._async_init(c)},wlb_async_update:function(g,c){a._async_update(c)}};f(document).bind("wlb_async_init",a.global_handlers.wlb_async_init).bind("wlb_async_update",a.global_handlers.wlb_async_update);b.attr("data-initialized",1)}else{"consoleLog"in window&&consoleLog("Requires option model.tconst or data-tconst attribute",
"wlb-lite");a._set_state("error")}},destroy:function(){f("a.btn2",this.element).unbind(".wlb_lite");f(document).unbind("wlb_async_init",this.global_handlers.wlb_async_init).unbind("wlb_async_update",this.global_handlers.wlb_async_update);f.ui.imdb_btn2.prototype.destroy.apply(this,arguments)},_is_attached:function(){return this.element.parents("body").length>0},_async_init:function(a){var b=this.element,e=this.options.model;if(!this._is_attached())return this.destroy();e.extra=a.extra;e.list_id=a.list_id;
if(a.checked[e.tconst]){"consoleLog"in window&&consoleLog("initialization complete","wlb_lite");if(a.has[e.tconst]){e.list_item_id=a.has[e.tconst][0];this._set_state("in")}else this._set_state("out");b.trigger("wlb_ready",{tconst:e.tconst,inwatchlist:a.has[e.tconst]})}},_async_update:function(a){var b=this.options.model;if(!this._is_attached())return this.destroy();if(a.list_class==="watchlist"&&b.list_id==="watchlist")b.list_id=a.list_id;if(b.tconst===a.tconst&&b.list_id===a.list_id)if(a.list_item_id){this._set_state("in");
b.list_item_id=a.list_item_id}else{this._set_state("out");b.list_item_id=null}},_set_state:function(a){this.options.model.state=a;this._ui_render()},_ui_render:function(){var a=this.element,b=this.options.model,e=b.assets.title[b.state],g=b.assets.glyph[b.state];this.modifyText(b.assets.text[b.state]);this.modifyGlyph(g);f("a.btn2",a).attr("title",e)},_request_toggle:function(){var a=this,b=a.element,e=a.options.model,g;b.trigger("wlb_user_interaction");if(h()){if(!(e.state==="loading"||e.state===
"error"||e.state==="pending")){a._set_state("pending");var c=null;if(e.list_item_id){g="/list/_ajax/edit";c={action:"delete",list_id:e.list_id,list_item_id:e.list_item_id,ref_tag:e.caller_name}}else if(e.list_id==="watchlist"){g="/list/_ajax/watchlist_add";c={tconst:e.tconst,lcn:e.caller_name}}else{g="/list/_ajax/edit";c={"const":e.tconst,list_id:e.list_id,ref_tag:e.caller_name}}if(e.extra)c[e.extra.name]=e.extra.value;f.ajax({url:g,type:"POST",data:c,beforeSend:window.addClickstreamHeadersToAjax,
error:function(){"consoleLog"in window&&consoleLog("failed to toggle membership","wl_button");a._set_state("error")},success:function(j){if(j.status!=200)return this.error();if(j.list_id)e.list_id=j.list_id;b.trigger("wlb_async_update",{tconst:e.tconst,list_id:e.list_id,list_class:"watchlist",list_item_id:j.list_item_id})}})}}else a._activate_login_lightbox()},_activate_login_lightbox:function(){"consoleLog"in window&&consoleLog("request login","wlb_lite");f("#nblogin").click()}});f.fn.wlb_lite=function(){var a=
f(this).not("[data-initialized=1]"),b=f.fn.wlb_lite_base.apply(this,arguments),e=[],g={};if(a.length===0)return b;if(typeof arguments[0]==="string")return b;if(h()){a.each(function(){var c=f(this).data("tconst");if(c&&c.length!=0&&!g[c]){g[c]=true;e.push(c)}});f.ajax({url:"/list/_ajax/watchlist_has",type:"POST",data:{consts:e,tracking_tag:"wlb-lite"},beforeSend:window.addClickstreamHeadersToAjax,error:function(){"consoleLog"in window&&consoleLog("watchlist_has request failed","wl_button")},success:function(c){if(c.status!=
200)return this.error();a.first().trigger("wlb_async_init",{list_id:c.list_id||"watchlist",has:c.has,checked:g,extra:c.extra})}})}return b}})(jQuery);(function(f){if(!f(document).data("wl-button-analytics")){f(document).data("wl-button-analytics",true);if(!("_gaq"in window))window._gaq=[];f(document).bind("wlb_async_update",function(h,d){h=f(h.target);var a=f("a",h).filter("[data-list-id="+d.list_id+"]"),b=h.attr("data-tconst"),e=h.attr("data-ga-identifier")||h.attr("data-caller-name")||h.closest("[data-caller-name]").attr("data-caller-name"),g="watchlist",c="add_from";if(a.closest(".wlb_dropdown").length>0)g="list";d.list_item_id||(c="remove_from");
_gaq.push(["_trackEvent",g,c+"_"+e,b]);_gaq.push(function(){consoleLog(g+" "+c+" "+e+" "+d.tconst,"gaq")})})}})(jQuery);
